### ISSUE TITLE
✨[Week2] 2주차 세미나 수업

### ISSUE THREAD

**Issue by wjdalswl** [NOW-SOPT-iOS-Part/JeongMinJi-practice#7]
## 📝 개요
- 2주차 세미나 수업

## ✔️ To-Do
- [x] DelegatePattern 사용해서 데이터 전달 해보기
- [x] Closure 사용해서 데이터 전달해보기
- [x] NSLayoutConstraint 사용해서 AutoLayout 적용해보기
- [x] SnapKit 사용해서 AutoLayout 적용해보기
- [x] ScrollView 사용해보기

## 👀 ETC
- https://eunjin3786.tistory.com/465
- https://taekki-dev.tistory.com/33
